import { Listr } from "listr2";
import { execa, ExecaError } from "execa";
import fg from "fast-glob";
import pc from "picocolors";
import { readFileSync, writeFileSync, existsSync, rmSync, mkdirSync } from "fs";
import { resolve } from "path";

// ─── Types ──────────────────────────────────────────────────────────
interface Task {
  name: string;
  description: string;
  domain: string;
}

// ─── Config ──────────────────────────────────────────────────────────
const ROOT = resolve(process.cwd());
const TASKS_DIR = resolve(ROOT, ".opencode/tasks");
const PLAN_FILE = resolve(ROOT, "plan.md");
const TEST_CMDS: Record<string, string[]> = {
  backend: ["php artisan test", "cd .. && php artisan test"],
};

// ─── Helpers ──────────────────────────────────────────────────────────
function log(emoji: string, msg: string) {
  console.log(`${emoji}  ${msg}`);
}

async function ex(cmd: string, opts?: Record<string, any>): Promise<string> {
  try {
    const r = await execa(cmd, {
      shell: true,
      cwd: ROOT,
      timeout: 120_000,
      ...opts,
    });
    return r.stdout;
  } catch (e) {
    const err = e as ExecaError;
    return err.stdout ?? err.stderr ?? String(e);
  }
}

// ─── Load Tasks ──────────────────────────────────────────────────────
async function loadTasks(): Promise<Task[]> {
  const files = await fg.glob("**/*.md", { cwd: TASKS_DIR });
  const tasks: Task[] = [];

  for (const f of files) {
    const content = readFileSync(resolve(TASKS_DIR, f), "utf-8");
    const domain = f.split(/[\/\\]/)[0];
    for (const line of content.split("\n")) {
      const m = line.match(/^\s*[-*]\s*\[.\]\s*(.+?)(?:\s*[-–]\s*(.+))?$/);
      if (m) {
        tasks.push({
          name: m[1].trim(),
          description: m[2]?.trim() ?? "",
          domain,
        });
      }
    }
  }
  return tasks.length > 0 ? tasks : getFallback();
}

function getFallback(): Task[] {
  return [
    {
      name: "Run backend tests",
      description: "Verify all tests pass",
      domain: "backend",
    },
  ];
}

// ─── Phase 1: Planning (Read-Only + plan.md) ─────────────────────────
async function phasePlanning(task: Task): Promise<void> {
  log("🧠", `Planning: ${pc.bold(task.name)}`);

  const files = await fg.glob(
    [
      `**/*${task.name.replace(/\s+/g, "*")}*`,
      `**/${task.domain}/**/*.md`,
      `**/${task.domain}/**/*.php`,
    ],
    {
      cwd: ROOT,
      ignore: [
        "node_modules/**",
        "vendor/**",
        ".git/**",
        ".pipeline-worktrees/**",
      ],
    },
  );

  const plan = [
    `# Plan: ${task.name}`,
    ``,
    `**Description:** ${task.description || "—"}`,
    `**Domain:** ${task.domain}`,
    ``,
    `## Related Files`,
    ...(files.length ? files.map((f) => `- \`${f}\``) : ["- (none)"]),
    ``,
    `## Steps`,
    `- [ ] \`${task.domain}\` — ${task.description}`,
    ``,
    `## Verification`,
    `- \`${TEST_CMDS[task.domain]?.[0] || "php artisan test"}\``,
    ``,
    `---`,
    `*Generated by pipeline.ts – Planning*`,
  ];

  writeFileSync(PLAN_FILE, plan.join("\n"), "utf-8");
  log("📋", `Plan → ${pc.cyan("plan.md")}`);
}

// ─── Phase 2: Execution (Branch + Commit + Test) ─────────────────────
async function phaseExecution(): Promise<void> {
  if (!existsSync(PLAN_FILE)) {
    log("⚠️", `${pc.yellow("No plan.md found — skipping execution")}`);
    return;
  }

  const branch = `pipeline/${Date.now()}`;
  const currentBranch = (await ex("git rev-parse --abbrev-ref HEAD")).trim();

  // Commit all current changes onto a new branch
  const steps = [
    {
      title: `Create branch ${pc.cyan(branch)}`,
      task: async () => ex(`git checkout -b ${branch}`),
    },
    { title: "Stage all changes", task: async () => ex(`git add -A`) },
    {
      title: "Commit",
      task: async () => {
        const out = await ex(
          `git commit -m "wip: pipeline execution" --no-verify 2>&1`,
        );
        if (out.includes("nothing to commit"))
          log("ℹ️", "No changes to commit");
      },
    },
    {
      title: "Run backend tests",
      task: async (_, task: any) => {
        for (const cmd of TEST_CMDS.backend ?? []) {
          const out = await ex(cmd);
          if (out.includes("FAIL") || out.includes("ERROR")) {
            log("❌", `Tests failed:\n${out.slice(0, 500)}`);
            throw new Error("Tests failed");
          }
        }
        log("✅", "All tests passed");
      },
    },
    {
      title: `Push ${pc.cyan(branch)}`,
      task: async () => ex(`git push origin ${branch}`),
    },
  ];

  const ctx: any = {};
  await new Listr(steps, { rendererOptions: { collapseSubtasks: false } }).run(
    ctx,
  );
  ctx.branchName = branch;
  return ctx;
}

// ─── Phase 3: Review & Simplify ──────────────────────────────────────
async function phaseReview(): Promise<void> {
  log("🔍", "Review & Simplify");

  const modified = (await ex(`git diff --name-only HEAD~1..HEAD`))
    .split("\n")
    .filter(Boolean);

  // PHP CS Fixer for changed PHP files
  const phpFiles = modified.filter((f) => f.endsWith(".php"));
  if (
    phpFiles.length > 0 &&
    existsSync(resolve(ROOT, "backend/vendor/bin/php-cs-fixer"))
  ) {
    await ex(
      `php backend/vendor/bin/php-cs-fixer fix --allow-risky=yes --quiet 2>&1 || true`,
    );
    log("✅", "PHP CS Fixer");
  }

  // Prettier for changed TS/JS files
  const tsFiles = modified.filter((f) => /\.(ts|tsx|js|jsx|json|md)$/.test(f));
  if (tsFiles.length > 0) {
    await ex(
      `npx prettier --write ${tsFiles.join(" ")} --ignore-path .gitignore 2>&1 || true`,
    );
    log("✅", "Prettier");
  }

  const status = await ex("git status --porcelain");
  if (status.trim()) {
    await ex(`git add -A`);
    await ex(
      `git commit -m "refactor: simplify and optimize code structure" --no-verify`,
    );
    await ex(
      `git push origin ${(await ex("git rev-parse --abbrev-ref HEAD")).trim()}`,
    );
    log("📦", "Refactor commit pushed");
  } else {
    log("ℹ️", "No linting changes — skipping refactor commit");
  }
}

// ─── Phase 4: Delivery & Cleanup ──────────────────────────────────────
async function phaseDelivery(branchName?: string): Promise<void> {
  log("🚀", "Delivery");

  const branch =
    branchName ?? (await ex("git rev-parse --abbrev-ref HEAD")).trim();
  const planContent = existsSync(PLAN_FILE)
    ? readFileSync(PLAN_FILE, "utf-8")
    : "";
  const steps = planContent.match(/`[^`]+`\s*[-–]\s*.+/g) ?? [];

  const body = [
    "## Summary",
    `Automated pipeline execution.`,
    "",
    "## Changes",
    ...steps.map((s) => `- ${s.replace(/`/g, "")}`),
    "",
    "## Verification",
    "- `php artisan test`",
    "",
    "*Generated by pipeline.ts*",
  ].join("\n");

  const title = `pipeline: ${steps.length} file(s) modified`;

  const prUrl = await ex(
    `gh pr create --base main --head "${branch}" --title "${title}" --body "${body.replace(/"/g, '\\"')}" 2>&1 || true`,
  );

  if (prUrl && (prUrl.includes("github.com") || prUrl.includes("https://"))) {
    log("🔗", `PR → ${pc.cyan(prUrl.trim())}`);
  } else {
    log("⚠️", `${pc.yellow("gh CLI not available — manual PR:")}`);
    log("📌", `Branch: ${pc.cyan(branch)}`);
  }

  // Cleanup
  if (existsSync(PLAN_FILE)) {
    rmSync(PLAN_FILE, { force: true });
    log("🧹", "plan.md removed");
  }

  await ex("git checkout main");
  log("✅", "Back on main");
}

// ─── Main ─────────────────────────────────────────────────────────────
async function main() {
  const args = process.argv.slice(2);

  console.log(pc.cyan(pc.bold("\n╔══════════════════════════════════════╗")));
  console.log(pc.cyan(pc.bold("║   🔁  Beza AI Pipeline v2           ║")));
  console.log(pc.cyan(pc.bold("╚══════════════════════════════════════╝\n")));

  // Support single-phase mode: --phase <name>
  const phaseIdx = args.indexOf("--phase");
  if (phaseIdx !== -1 && args[phaseIdx + 1]) {
    const phase = args[phaseIdx + 1];
    const tasks = await loadTasks();
    switch (phase) {
      case "planning":
        return phasePlanning(tasks[0] ?? getFallback()[0]);
      case "execution":
        return phaseExecution();
      case "review":
        return phaseReview();
      case "delivery":
        return phaseDelivery();
    }
  }

  // Full 4-phase loop
  const tasks = await loadTasks();
  log("📋", `${pc.bold(String(tasks.length))} task(s) loaded\n`);

  for (let i = 0; i < tasks.length; i++) {
    const task = tasks[i];
    console.log(
      pc.yellow(pc.bold(`\n▸ [${i + 1}/${tasks.length}] ${task.name}`)),
    );

    const execCtx = await new Listr(
      [
        {
          title: "🧠  Planning",
          task: () => phasePlanning(task),
        },
        {
          title: "🛠️  Execution",
          task: () => phaseExecution(),
        },
      ],
      { rendererOptions: { collapseSubtasks: false }, exitOnError: true },
    ).run();

    // phaseExecution returns ctx; extract branchName
    const branchName = execCtx?.branchName;

    try {
      await new Listr(
        [
          {
            title: "🔍  Review & Simplify",
            task: () => phaseReview(),
          },
          {
            title: "🚀  Delivery",
            task: () => phaseDelivery(branchName),
          },
        ],
        { rendererOptions: { collapseSubtasks: false } },
      ).run();
    } catch (err) {
      log("⚠️", `${pc.yellow("Post-execution phase skipped")}`);
    }
  }

  log("\n🎉", pc.green(pc.bold("Pipeline complete!")));
}

main().catch((err) => {
  console.error(pc.red("Fatal:"), err);
  process.exit(1);
});
