export const ENDPOINTS = {
  ADMIN_LOGIN: "/v1/admin/login",
  ADMIN_ME: "/v1/admin/me",
  ADMIN_LOGOUT: "/v1/admin/logout",
  ADMIN_WAP_SUMMARY: "/v1/admin/wap/summary",
  ADMIN_WAP_DEVICES: "/v1/admin/wap/devices",
  ADMIN_WAP_QUEUE: "/v1/admin/wap/queue",
  ADMIN_WAP_ROUTES: "/v1/admin/wap/routes",
  ADMIN_WAP_ROUTE_UPDATE: (id: number) => `/v1/admin/wap/routes/${id}`,
  ADMIN_AGENTS: "/v1/admin/agents",
  ADMIN_AGENT_DETAIL: (id: number) => `/v1/admin/agents/${id}`,
  ADMIN_AGENT_APPROVE: (id: number) => `/v1/admin/agents/${id}/approve`,
  ADMIN_AGENT_SUSPEND: (id: number) => `/v1/admin/agents/${id}/suspend`,
  ADMIN_AGENT_COMMISSIONS: "/v1/admin/agents/commissions",
  ADMIN_AGENT_SETTLEMENTS: "/v1/admin/agents/settlements",
  ADMIN_AGENT_FRAUD_ALERTS: "/v1/admin/agents/fraud-alerts",
} as const;
